apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Nexgen
  title: nexgen
  description: Next Generation Nexus Generator 
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: DiamondLightSource/nexgen
  tags:
    - Python
    - Nexus
spec:
  type: application
  lifecycle: production
  owner: group:data-acquisition